### ISSUE TITLE
Close button in iframe doesn't call onCancel callback

### ISSUE THREAD

**Issue by bluepnume** [paypal/paypal-checkout#211]

**Comment by bluepnume** [comment]
Fixed and ready for push.

**Comment by bluepnume** [comment]
Fixed and pushed.

**Comment by bluepnume** [comment]
Actually this didn't make it into the recent build. Reopening.

**Comment by bluepnume** [comment]
Fixed and pushed.

**Comment by joweste** [comment]
Sorry, but is not fixed using angularjs and latest checkout.js version
