### ISSUE TITLE
IE 11 not rendering paypal express button because of syntax error.

### ISSUE THREAD

**Issue by smh974** [paypal/paypal-checkout#310]
On Internet Explorer 11 on the latest browser you will get a syntax error from the button which is causing it not to render properly. Example of this happening is on the demo checkout for paypal.

https://developer.paypal.com/demo/checkout/#/pattern/client

**Comment by bluepnume** [comment]
Hey thanks for the catch. Seems like babel isn't compiling that function correctly. I'm pushing a quick fix as we speak. Will let you know.

**Comment by bluepnume** [comment]
OK, this should be resolved. Can you please try your browser cache and try once more? 

Thanks again for raising this, appreciate it.

**Comment by smh974** [comment]
Almost there. The text is showing up but it looks black. Not the correct colors. I believe there is a syntax error in the button javascript. If you look in the console you will see it on line 476. I believe it is related to ES6.

**Comment by smh974** [comment]
If you look at the previous example you will see the text and image not looking quite right.
https://developer.paypal.com/demo/checkout/#/pattern/client

**Comment by bluepnume** [comment]
Do you have a screenshot? I'm seeing it render ok on my side.

**Comment by smh974** [comment]
![paypalimage](https://cloud.githubusercontent.com/assets/7681254/25505424/37992cdc-2b67-11e7-91b2-5550dc68b66a.PNG)

You can see that it is showing up as black for the button image.

**Comment by bluepnume** [comment]
Woah, very strange. I suspect this is a problem with the css not being applied to the paypal svg correctly, but let me try to repro. Weirdly, it looks fine in my instance of IE11.

Out of interest, does the color initially appear ok and then render black, or is it that way from the first moment it renders?

**Comment by smh974** [comment]
From what I can tell it is black from the moment that it renders.

**Comment by smh974** [comment]
![ieabout](https://cloud.githubusercontent.com/assets/7681254/25506054/436564a6-2b6a-11e7-8a72-35138fd8e69f.PNG)
Not sure if this helps but here is my version information on IE 11

**Comment by bluepnume** [comment]
@smh974 could you possibly grab a screenshot of this page for me? Still unable to repro but trying to narrow this down.

http://www.bluesuncorp.co.uk/icv4/test.htm

Thanks!

**Comment by smh974** [comment]
![paypalimagessnip](https://cloud.githubusercontent.com/assets/7681254/25544907/3c556b12-2c22-11e7-9d88-4157baa9d765.PNG)
This images shows up as black as well.

**Comment by bluepnume** [comment]
Hmm. Grasping at straws here. Any changes here now? http://www.bluesuncorp.co.uk/icv4/test.htm

**Comment by smh974** [comment]
Looks like the bottom icons are correct now.
![correctbottomicons](https://cloud.githubusercontent.com/assets/7681254/25619223/b5c805dc-2f0f-11e7-8f54-c9b987e66de9.PNG)

**Comment by bluepnume** [comment]
OK, thanks again for your help! I think I've identified the difference between these logos that's causing your problem. Could you please try clearing your browser cache and trying the latest checkout.js? I pushed out a fix this morning that should work for you.

**Comment by smh974** [comment]
Sorry for the delay. I just had a chance to test this. Still having the problem with the black text unfortunately. 
![latestpaypal](https://cloud.githubusercontent.com/assets/7681254/25713778/74a0f4a8-30bb-11e7-9573-49b5060395e5.PNG)

**Comment by bluepnume** [comment]
Ah nuts. Can you confirm the `paypal.version` you see in your console?

**Comment by bluepnume** [comment]
Note -- just pushed out a new version of the button. Would be useful to know if you still see the problem after clearing cache, and if so, what `paypal.version` you get in your console.

**Comment by smh974** [comment]
I just tested this on IE 11 today and the colors are correct! Thanks for your hard work on this!

**Comment by bluepnume** [comment]
Woot! Really glad it's working now. Thanks again for taking the time to help me verify all of these changes.
