### ISSUE TITLE
pt_BR Buy Now button is blank 

### ISSUE THREAD

**Issue by bsweetnam** [paypal/paypal-checkout#439]
for pt_BR locale, there is no button text when button size is small and branding is turned off.  

Please provide a short description of the issue here, along with:
![image](https://user-images.githubusercontent.com/22103168/29292610-95f7557a-80fc-11e7-91c0-38f39ee625f2.png)

**Comment by iamrudra** [comment]
Fiddling around, I found the same with `es_ES`

![image](https://user-images.githubusercontent.com/12117759/29295922-fe474a22-810b-11e7-93e2-a4fb4a7f0d7d.png)

**Comment by bluepnume** [comment]
Actually I think @vishakha94 may have fixed this already but the fix didn't make it out yet. Hopefully with tomorrow's Hermes release.

**Comment by vishakha94** [comment]
This has been fixed but is not live it. Will close it once after today's push.

**Comment by bluepnume** [comment]
@vishakha94 I don't think this got fixed -- I still see `width: 60%` but I think we need `width: auto` otherwise the text will cut off if it's greater than `60%`.

DW about it though, I'm doing some refactoring to add the credit dual button so I'll slot this in.

**Comment by bluepnume** [comment]
Fixed and pushed.
