### ISSUE TITLE
Credit card icons  disappearing with  a "Buy Now Button", issue present in Demo

### ISSUE THREAD

**Issue by stefanaz** [paypal/paypal-checkout#866]
### Description

Today I observe an issue with a "Buy Now Button". 
The credit card icons below the button disappear after 1-2 seconds, after they are loaded. 
The things were working for me yesterday and last month so I could miss some update from PayPal, but this issue is also present at the "Demo": 

https://developer.paypal.com/demo/checkout/#/pattern/buynow

Could you please help me with that? 
Or please help me to find another similar solution so my customers could use credit cards options? 

Thanks!  

### Steps to reproduce

Issue is visible here as well: 
https://developer.paypal.com/demo/checkout/#/pattern/buynow

The issue is not present for a Firefox browser.

### Affected browsers

- [x] Chrome
- [x] Safari
- [ ] Firefox
- [x] Edge
- [x] IE
- [x] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by stefanaz** [comment]
Hi again, I have found hotfix for that. 

        style: {
            label: 'buynow',
            //fundingicons: true, // optional
            layout: 'vertical',  // horizontal | vertical
            branding: true, // optional
            size:  'responsive', // small | medium | large | responsive
            shape: 'rect',   // pill | rect
            color: 'blue'   // gold | blue | silver | black
        },

Next lines do the trick: 
            //fundingicons: true, // optional
            layout: 'vertical',  // horizontal | vertical

**Comment by dimrun** [comment]
Hi, we have the same issue with disappearing button. Although, we don't use fundingicons and layout.
Browser: Chrome

**Comment by bill-z** [comment]
We're seeing the same issue. The "Buy Now" button initially appears on the page with card images, and then (apparently after a call to https://www.sandbox.paypal.com/webapps/hermes/button ?)
the cards disappear and the font of the "Buy Now" text changes (from more vertical letters, to more slanted/italic letters). 

Of course, I was hoping to demo our new PayPal integration _today_. (and those cards are important)

**Comment by stefanaz** [comment]
@bill-z  does layout: 'vertical' set help in your case?

**Comment by bill-z** [comment]
The https://www.sandbox.paypal.com/webapps/hermes/button call is unrelated. If I block the network call I see the same behavior.

**Comment by abarco** [comment]
Hi all,
Thank you for reporting this. We've identified the problem and we're working on resolving it. We'll update this issue once a new version of the script is published.

**Comment by abarco** [comment]
The fix has been pushed. @stefanaz please clear your cache and re-try rendering your button. Sorry for the inconvenience.

**Comment by bill-z** [comment]
@abarco: thanks for the quick fix. 
 
The card images are now displaying again, but I still see the font of the "Buy Now" text change at about the same time the cards were disappearing (~1 sec(?) after first displayed).  (font changes to italic)

I first saw this with the card issue.  Hopefully they are related(?).

before:
![image](https://user-images.githubusercontent.com/995131/45909446-742c4500-bdc7-11e8-8e56-9fa86045d0bc.png)

after:
![image](https://user-images.githubusercontent.com/995131/45909434-624aa200-bdc7-11e8-84da-3dd84c1abb32.png)

**Comment by stefanaz** [comment]
@abarco,  thanks, seems to be working now, except the italic font after 1sec. 
But in my case it is not so important.

**Comment by abarco** [comment]
Hi guys, thanks for verifying the fix. I'll be closing out this issue now. 
For the italics problem, we have a fix coming soon that should be taking care of that issue. Please create a separate issue so it can be tracked as it is separate from this one.
